//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("GitHub Client")]
[assembly: AssemblyCompany("Illallangi Enterprises")]
[assembly: AssemblyProduct("GitHub Client")]
[assembly: AssemblyCopyright("Copyright © Illallangi Enterprises 2014")]
[assembly: ComVisible(false)]
[assembly: AssemblyInformationalVersion("Built from hash \'cabfbf9\'")]
[assembly: Guid("91ce24d2-34cb-46c2-9511-9f186c75b5e3")]
[assembly: AssemblyVersion("0.0.0.1")]
[assembly: AssemblyFileVersion("0.0.0.1")]


